{"commit_hash": "ec1b4ce759f1fb8ba0242dd6c4a309fa1b586666", "commit_msg": "Fix to allow cvx_fit to retry and finally gracefully fail if the solver cannot handle the problem (#3)", "project_name": "qiskit-ignis", "id": "1", "human_id": "qiskit-ignis#3", "author_comment": "From fixer: \"Currently, cvx_fit does not check the success of the prob.solve() call. When the solver fails, this results in a crash on the following line: rho_fit = rho_r.value + 1j * rho_i.value\""}